// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSraLt_BfeWAmCV58Pt_hX22eNYNv4QGs',
    appId: '1:229755449825:web:bd1ce0499d2f9cb791a2a0',
    messagingSenderId: '229755449825',
    projectId: 'task-management-app-e84b2',
    authDomain: 'task-management-app-e84b2.firebaseapp.com',
    storageBucket: 'task-management-app-e84b2.appspot.com',
    measurementId: 'G-0FF0STYDH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAemKRoPJ4yC8gR1vqITv5eJHIb8eygTEQ',
    appId: '1:229755449825:android:35749a62356aae0d91a2a0',
    messagingSenderId: '229755449825',
    projectId: 'task-management-app-e84b2',
    storageBucket: 'task-management-app-e84b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAustkpa-gnCYxAyzsyx5Kw3S45ElN6rjA',
    appId: '1:229755449825:ios:e7e64a4b7d21b82f91a2a0',
    messagingSenderId: '229755449825',
    projectId: 'task-management-app-e84b2',
    storageBucket: 'task-management-app-e84b2.appspot.com',
    iosClientId: '229755449825-ljv8ig64nuvqjbq6vsgqq6sftgfhlikh.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAustkpa-gnCYxAyzsyx5Kw3S45ElN6rjA',
    appId: '1:229755449825:ios:e7e64a4b7d21b82f91a2a0',
    messagingSenderId: '229755449825',
    projectId: 'task-management-app-e84b2',
    storageBucket: 'task-management-app-e84b2.appspot.com',
    iosClientId: '229755449825-ljv8ig64nuvqjbq6vsgqq6sftgfhlikh.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagerApp',
  );
}
